# Generated by Django 5.1.3 on 2024-12-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGalleryCerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.certificates')),
            ],
            options={
                'verbose_name': 'certgallery',
                'verbose_name_plural': 'certificate gallery',
            },
        ),
    ]
